services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.11
    container_name: clickhouse_container
    environment:
      - CLICKHOUSE_USER=ch_user
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./sql:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
volumes:
  ch_data: